#!/usr/bin/env bash
set -euo pipefail

# file: scripts/inventory/export_repos.sh
# repo: homelab_global
# owner: alex
# created: 2026-01-17
# last_reviewed: 2026-01-17
# purpose: Deterministically export repo inventory (personal + org) into SSOT docs.
# tags: [inventory, github, automation, ssot]

: "${GITHUB_TOKEN:?Set GITHUB_TOKEN in env (do not commit).}"

api() {
  local url="$1"
  curl -fsSL \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$url"
}

fetch_all_pages() {
  local url_base="$1" page=1
  while :; do
    local url="${url_base}&page=${page}"
    local body
    body="$(api "$url")"
    local count
    count="$(jq 'length' <<< "$body")"
    ((count == 0)) && break
    jq -c '.[]' <<< "$body"
    ((page++))
  done
}

get_me_login() { api "https://api.github.com/user" | jq -r '.login'; }

write_md_header() {
  cat << 'H'
<!--
file: docs/inventory/01-repos-raw.md
repo: homelab_global
owner: alex
created: 2026-01-17
last_reviewed: 2026-01-17
purpose: Raw, sanitized repo inventory captured from GitHub (no tokens, no secrets). Generated automatically.
tags: [inventory, repos, migration, ssot]
-->

# Repo inventory (generated)

## Rules (hard)
- Never commit API tokens / PATs / auth headers.
- Never commit private keys or cert private keys (`*.key`, `*.pem`).
- This file is generated by `scripts/inventory/export_repos.sh`. Do not hand-edit lists.
H
}

emit_repo_lines_md() {
  # expects JSON lines of repos
  while IFS= read -r repo; do
    local full url vis fork lang
    full="$(jq -r '.full_name' <<< "$repo")"
    url="$(jq -r '.html_url' <<< "$repo")"
    vis="$(jq -r '.visibility' <<< "$repo")"
    fork="$(jq -r '.fork' <<< "$repo")"
    lang="$(jq -r '.language // ""' <<< "$repo")"
    printf -- "- %s (%s, fork=%s, lang=%s): %s\n" "$full" "$vis" "$fork" "${lang:-}" "$url"
  done
}

emit_repo_rows_csv() {
  # expects JSON lines of repos
  while IFS= read -r repo; do
    local full vis fork lang
    full="$(jq -r '.full_name' <<< "$repo")"
    vis="$(jq -r '.visibility' <<< "$repo")"
    fork="$(jq -r '.fork' <<< "$repo")"
    lang="$(jq -r '.language // ""' <<< "$repo")"
    printf '%s,%s,%s,%s,,,,,\n' "$full" "$vis" "$fork" "$lang"
  done
}

main() {
  local me
  me="$(get_me_login)"
  local out_md="docs/inventory/01-repos-raw.md"
  local out_csv="docs/inventory/02-repos-classified.csv"

  mkdir -p docs/inventory

  # Personal repos of the authenticated user (includes private when token allows).
  # /user/repos lists repos for the token's user; supports visibility=all.
  local personal_json
  personal_json="$(fetch_all_pages "https://api.github.com/user/repos?per_page=100&visibility=all&affiliation=owner,collaborator,organization_member")"

  # Org repos (atnplex); includes private when token has access.
  local org_json
  org_json="$(fetch_all_pages "https://api.github.com/orgs/atnplex/repos?per_page=100&type=all")"

  {
    write_md_header
    echo
    echo "## Sources"
    echo "- Authenticated user: ${me}"
    echo "- Organization: atnplex"
    echo
    echo "### ${me}/*"
    printf '%s\n' "$personal_json" | emit_repo_lines_md
    echo
    echo "### atnplex/*"
    printf '%s\n' "$org_json" | emit_repo_lines_md
  } > "$out_md"

  {
    echo "repo_full_name,visibility,is_fork,primary_language,category,keep_or_archive,target_owner,target_repo,action,notes"
    printf '%s\n' "$personal_json" | emit_repo_rows_csv
    printf '%s\n' "$org_json" | emit_repo_rows_csv
  } > "$out_csv"

  echo "[inventory] wrote: $out_md"
  echo "[inventory] wrote: $out_csv"
}
main "$@"
